name: Build

on: [push, pull_request]

jobs:
  windows-build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: "2022"
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"
          directory: ${{ runner.temp }}/llvm
      - uses: lukka/get-cmake@latest
      - name: Build project
        env:
          CC: clang
          CXX: clang++
        # Use Ninja generator to enable clang-tidy as Visual Studio generator doesn't create compilation database
        run: |
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_WERROR=ON -DENABLE_CLANG_TIDY=ON
          cmake --build build --config Release -v
      - name: Generate ZIP package
        working-directory: build
        run: |
          cpack -C "Release" -V
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/3DRenderer-*.zip

  linux-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/AppImage/AppImageKit/wiki/FUSE
      - name: Install dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install libfuse2 libwayland-dev libxkbcommon-dev xorg-dev
      - uses: lukka/get-cmake@latest
      - name: Build project
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_WERROR=ON -DENABLE_CLANG_TIDY=ON
          cmake --build build --config Release -v
      - name: Generate AppImage package
        working-directory: build
        run: |
          make install DESTDIR=. VERBOSE=1
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            3DRenderer-*.AppImage

  web-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libwayland-dev libxkbcommon-dev xorg-dev
      - uses: lukka/get-cmake@latest
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.64
      - name: Build project
        run: |
          emcmake cmake \
            -DWEBBUILD_CI=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_WERROR=ON \
            -DENABLE_CLANG_TIDY=ON \
            -DCMAKE_INSTALL_PREFIX=dist \
            .
          emmake make VERBOSE=1
          emmake make install VERBOSE=1
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
