name: Build

on: [push, pull_request]

jobs:
  windows-build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: "2022"
      - name: Set compiler environment for Windows
        uses: lukka/set-shell-env@v1
        with:
          CXX: cl.exe
          CC: cl.exe
      - uses: lukka/get-cmake@latest
      - name: Build project
        # TODO: Outdated, make sure to update without breaking CI
        uses: lukka/run-cmake@v3
        with:
          # HACK: Windows CI hallucinates clang-tidy errors that are not even there, possibly due to PCH
          cmakeAppendedArgs: "-DCMAKE_BUILD_TYPE=Release -DBUILD_WERROR=ON -DENABLE_CLANG_TIDY=OFF"
          buildDirectory: "${{ github.workspace }}/build/"
      - name: Generate ZIP package
        working-directory: build
        run: |
          cpack -C "Release"
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/3DRenderer-*.zip

  linux-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/AppImage/AppImageKit/wiki/FUSE
      - name: Install dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install libfuse2 libwayland-dev libxkbcommon-dev xorg-dev
      - uses: lukka/get-cmake@latest
      - name: Build project
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_WERROR=ON -DENABLE_CLANG_TIDY=ON
          make -j`nproc`
      - name: Generate AppImage package
        run: |
          make install DESTDIR=.
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            3DRenderer-*.AppImage

  web-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libwayland-dev libxkbcommon-dev xorg-dev
      - uses: lukka/get-cmake@latest
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.64
      - name: Build project
        run: |
          emcmake cmake \
            -DWEBBUILD_CI=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_WERROR=ON \
            -DENABLE_CLANG_TIDY=ON \
            -DCMAKE_INSTALL_PREFIX=dist \
            .
          emmake make VERBOSE=1
          emmake make install VERBOSE=1
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
